# AWS SAM Template for FinSight - Lightweight Bedrock Integration
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  FinSight Lightweight Financial Fact-Checking API - Optimized for AWS Lambda
  
  A lightweight serverless API for financial fact-checking with minimal dependencies
  to avoid Lambda package size limits while maintaining core functionality.

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.11
    Environment:
      Variables:
        # System Configuration
        FINSIGHT_DEBUG: !Ref DebugMode

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Deployment stage
  
  DebugMode:
    Type: String
    Default: "true"
    AllowedValues: ["true", "false"]
    Description: Enable debug logging

Resources:
  # API Gateway
  FinancialAIApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  # Lightweight Fact Check Function
  LightweightFactCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../src/
      Handler: handlers.lightweight_fact_check_handler.lambda_handler
      Description: Lightweight financial fact-checking without heavy dependencies
      Timeout: 60
      MemorySize: 512
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource:
                - "arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-3-haiku-20240307-v1:0"
                - "arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-text-express-v1"
      Events:
        FactCheckApi:
          Type: Api
          Properties:
            RestApiId: !Ref FinancialAIApi
            Path: /fact-check
            Method: post

  # Health Check Function
  HealthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../src/
      Handler: handlers.health_handler.lambda_handler
      Description: API health check endpoint
      Events:
        HealthApi:
          Type: Api
          Properties:
            RestApiId: !Ref FinancialAIApi
            Path: /health
            Method: get

  # Root Info Function
  RootFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../src/
      Handler: handlers.root_handler.lambda_handler
      Description: API information endpoint
      Events:
        RootApi:
          Type: Api
          Properties:
            RestApiId: !Ref FinancialAIApi
            Path: /
            Method: get

  # CloudWatch Log Groups
  LightweightFactCheckLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${LightweightFactCheckFunction}'
      RetentionInDays: 7

  HealthCheckLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${HealthCheckFunction}'
      RetentionInDays: 7

  RootLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${RootFunction}'
      RetentionInDays: 7

Outputs:
  FinancialAIApiUrl:
    Description: "API Gateway endpoint URL for FinSight Lightweight API"
    Value: !Sub "https://${FinancialAIApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/"
    Export:
      Name: !Sub "${AWS::StackName}-ApiUrl"
  
  DeploymentInfo:
    Description: "Deployment configuration summary"
    Value: !Sub "Stage: ${Stage}, Lightweight: true, Debug: ${DebugMode}"
